trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.4'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run setup
    npm run build
    npm run package
  workingDirectory: Calling
  displayName: Run NPM tasks
  
- publish: Calling/dist
  
